resources:
  - name: target-branch
    type: git
    source:
      uri: ((repo_uri))
      branch: ((branch))
      private_key: ((private_key))
jobs:
  - name: build
    plan:
      - get: target-branch
        trigger: true
      - task: build
        config:
          platform: linux
          caches:
            - path: $HOME/.m2/repository
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.8.5-openjdk-17
          inputs:
            - name: target-branch
          run:
            path: sh
            args:
              - -cx
              - |
                cd target-branch
                ls -la $HOME
                mvn clean install
                ls -la $HOME/.m2
